before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/envosaurus/envosaurus.go
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
    ldflags:
      - -w -X github.com/simplifi/anemometer/pkg/anemometer/version.Version={{.Version}}
archives:
  - format: tar.gz
    files:
      - none*
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
